
export const LATTICE_RADIUS = 6;
export const INIT_CASTLETALK = 255;
export const PILGRIM_DANGER_CASTLETALK = 1;
export const PREACHER_CHURCH_INIT = 209;

export const CLUSTER_RADIUS = 5;
export const ENEMY_PREACHER = 15;
export const ENEMY_PROPHET = 14;
export const ENEMY_CRUSADER = 13;

export const WALL_FANOUT = 10;
export const WALL_WAIT = 20;


export const PILGRIM_JOBS = {
    MINE_KARBONITE: 0,
    MINE_FUEL: 1,
    BUILD_CHURCH: 2,
    BUILD_ENEMY_CHURCH: 3,
    OFFENSIVE: 4,
    BUILD_WALL: 5,
    SCOUT: 6,
    BUILD_WALL_SUBSEQUENT: 7,
    BUILD_PREACHER_CHURCH: 8
};

export const PILGRIM_MODE = {
    MOVE_TO_RESOURCE: 0,
    MINE_RESOURCE: 1,
    MOVE_TO_CASTLE: 2,
    FLEE: 3,
    MOVE_OFFENSIVE: 4,
    NOTHING: 5,
    MOVE_OFFENSIVE2: 6,
    SIGNAL_PREACHERS: 7
};

export const PROPHET_JOBS = {
    DEFEND_CASTLE:[0,1,2,3,4,5,6,7],
    REINFORCE_PILGRIM: 8,
    DEFEND_GOAL: 9,
    ATTACK_GOAL_LOWER: 10,
    ATTACK_GOAL_HIGHER:11,
    DEFEND_ENEMY_CHURCH:12,


};

export const PROPHET_MODE = {
    PATH_TO_GOAL: 0,
    DEFEND: 1,
    ATTACK: 2,
    REINFORCE: 3,
    DEFEND_CASTLE:4,
    MOVE_AWAY:5,
    PATH_TO_CHURCH: 6
};


export const PREACHER_JOBS = {
    DEFEND_CASTLE:[0,1,2,3,4,5,6,7],
    DEFEND_GOAL: 8,
    ATTACK_GOAL_LOWER: 10,
    ATTACK_GOAL_HIGHER:11,
    SUICIDE: 12,
    DEFEND_ENEMY_CHURCH: 13,
};

export const PREACHER_MODE = {
    DEFEND_CASTLE:0,
    ATTACK_CASTLE:1,
    PATH_TO_GOAL: 2,
    DEFEND: 3,
    ATTACK: 4,
    REINFORCE: 5,
    MOVE_TO_FRONT_LINES: 6,



    VICTORY: 7,
    PATH_TO_CHURCH: 8,

};
export const CRUSADER_JOBS = {
    DEFEND_GOAL: 0,
    DEFEND_ENEMY_CHURCH:1
};
export const CRUSADER_MODE = {
    PATH_TO_GOAL: 0,
    DEFEND: 1,
    CHAAAAAAAARGE:2,
    PATH_TO_CHURCH: 3,
    ATTACK: 4,

};





export const SIGNAL_CODE = {
    REQUEST_REASSIGN: 0,
    CASTLE_POS: 1,
    INIT_SIGNAL: 14,
    ALIVE_SIGNAL: 11,
    CREATE_ENEMY_CHURCH: 12,
    CREATE_FRIENDLY_CHURCH: 13,
    CREATE_OFFENSIVE_CHURCH: 6,
    SCOUT_INFO: 7,
    DONE_SCOUTING: 8,
    CREATE_PREACHER_CHURCH: 9,
    PREACHER_CHURCH_INIT: 10,
<<<<<<< HEAD
    ENEMY_PILGRIM : 2,
    ENEMY_CRUSADER : 3,
    ENEMY_PROPHET : 4,
    ENEMY_PREACHER : 5

=======
    PREACHER_VICTORY: 11
>>>>>>> 6547e999ecb640362c860927a9e9124da72b7967
};

export const PROPHET_SIGNAL_CODE = {

    ENEMY_CRUSADER : 3,
    ENEMY_PROPHET : 4,
    ENEMY_PREACHER : 5
}

